# for /merchant convert_token, set the name of a ball to use as a token
token_ball_name = "Valen"

# Coins received for each token converted when using /merchant convert_token
# Example: 1 token = 100 coins
token_conversion_rate = 150